# Generated by Django 4.2 on 2023-04-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='User id')),
                ('location', models.CharField(max_length=200, verbose_name='Geographic location')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='User biological age')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
