# Generated by Django 4.2 on 2023-04-28 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Book id')),
                ('title', models.CharField(max_length=200, verbose_name='Title of the book')),
                ('author', models.CharField(max_length=200, verbose_name='Author of the book')),
                ('year_publication', models.CharField(max_length=4, verbose_name='Year of publication')),
                ('publisher', models.CharField(max_length=4, verbose_name='Publisher name')),
                ('image_1', models.URLField(verbose_name='Book image 1')),
                ('image_2', models.URLField(verbose_name='Book image 2')),
                ('image_3', models.URLField(verbose_name='Book image 3')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
