# Generated by Django 4.2 on 2023-04-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_1',
            field=models.URLField(blank=True, null=True, verbose_name='Book image 1'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_2',
            field=models.URLField(blank=True, null=True, verbose_name='Book image 2'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_3',
            field=models.URLField(blank=True, null=True, verbose_name='Book image 3'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publisher name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_publication',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of publication'),
        ),
    ]
