# Generated by Django 4.2 on 2023-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(blank=True, null=True, verbose_name='Publisher name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_publication',
            field=models.TextField(blank=True, null=True, verbose_name='Year of publication'),
        ),
    ]
